const teamNameToCode = {
    "Germany": "GER",
    "France": "FRA",
    "Italy": "ITA",
    "Spain": "ESP",
    "England": "ENG",
    "Netherlands": "NED",
    "Portugal": "POR",
    "Czechia": "CZE",
    "Czechoslovakia": "TCH",
    "Greece": "GRE",
    "Russia": "RUS",
    "Soviet Union": "USSR",
    "Yugoslavia": "YUG",
    "Serbia": "SRB",
    "Switzerland": "SUI",
    "Sweden": "SWE",
    "Denmark": "DEN",
    "Belgium": "BEL",
    "Poland": "POL",
    "Austria": "AUT",
    "Croatia": "CRO",
    "Ukraine": "UKR",
    "Albania": "ALB",
    "Iceland": "ISL",
    "Wales": "WAL",
    "Ireland": "IRL",
    "Scotland": "SCO",
    "Turkey": "TUR",
    "Romania": "ROU",
    "Slovakia": "SVK",
    "Slovenia": "SVN",
    "Finland": "FIN",
    "Hungary": "HUN",
    "Norway": "NOR",
    "Latvia": "LVA",
    "North Macedonia": "MKD"
  };
  
  module.exports = teamNameToCode;
  